#!/usr/bin/env node
/**
 * Gallery album manager — All Nations Church NorthWest
 *
 * Turns a shared Google Photos album link into a password-protected album on
 * the Gallery page. The photo list and album link are encrypted (AES-256-GCM,
 * key derived from the password with PBKDF2), so neither the password nor the
 * Google links appear anywhere in the site's source. Only the cover image is
 * public; it is saved to assets/images/gallery/.
 *
 * Usage (run from the project folder):
 *   node tools/gallery.mjs add <google-photos-link> [--title "Name"] [--date "Month D, YYYY"]
 *   node tools/gallery.mjs refresh            re-sync every album with Google Photos
 *   node tools/gallery.mjs remove <album-id>
 *   node tools/gallery.mjs list
 *
 * The password is asked for each time (or pass --password, or set GALLERY_PASSWORD).
 * Every album must use the same password; the tool checks it against existing albums.
 */
import { readFile, writeFile, mkdir, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { webcrypto as crypto } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA_FILE = path.join(ROOT, 'js', 'gallery-data.js');
const COVER_DIR = path.join(ROOT, 'assets', 'images', 'gallery');
const ITERATIONS = 600000;
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36';

const b64 = buf => Buffer.from(buf).toString('base64');
const unb64 = s => new Uint8Array(Buffer.from(s, 'base64'));

/* ---------- args ---------- */
const argv = process.argv.slice(2);
const cmd = argv[0];
function flag(name) {
  const i = argv.indexOf(`--${name}`);
  return i > -1 ? argv[i + 1] : undefined;
}
const positional = argv.slice(1).filter((a, i, arr) => !a.startsWith('--') && !(arr[i - 1] || '').startsWith('--'));

/* ---------- data file ---------- */
async function loadVault() {
  if (!existsSync(DATA_FILE)) {
    return { kdf: { salt: b64(crypto.getRandomValues(new Uint8Array(16))), iterations: ITERATIONS }, albums: [] };
  }
  const src = await readFile(DATA_FILE, 'utf8');
  const m = src.match(/\/\*VAULT\*\/([\s\S]*)\/\*END\*\//);
  if (!m) throw new Error('Could not read js/gallery-data.js');
  return JSON.parse(m[1]);
}

async function saveVault(vault) {
  const out = `// Gallery albums. Generated by tools/gallery.mjs; edit with that tool, not by hand.
// Photo lists are encrypted and can only be opened with the gallery password.
const galleryVault = /*VAULT*/${JSON.stringify(vault, null, 2)}/*END*/;
`;
  await writeFile(DATA_FILE, out);
}

/* ---------- crypto (must match js/gallery.js) ---------- */
async function deriveKey(password, kdf) {
  const base = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt: unb64(kdf.salt), iterations: kdf.iterations, hash: 'SHA-256' },
    base, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']
  );
}
async function encrypt(key, obj) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const data = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(JSON.stringify(obj)));
  return { iv: b64(iv), data: b64(data) };
}
async function decrypt(key, album) {
  const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(album.iv) }, key, unb64(album.data));
  return JSON.parse(new TextDecoder().decode(plain));
}

/* ---------- password ---------- */
function ask(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(res => rl.question(question, a => { rl.close(); res(a); }));
}
async function getKey(vault) {
  const password = flag('password') || process.env.GALLERY_PASSWORD || await ask('Gallery password: ');
  if (!password) throw new Error('A password is required.');
  const key = await deriveKey(password, vault.kdf);
  if (vault.albums.length) {
    try { await decrypt(key, vault.albums[0]); }
    catch { throw new Error('That password does not match the existing albums.'); }
  }
  return key;
}

/* ---------- Google Photos scraping ---------- */
async function fetchAlbum(link) {
  const res = await fetch(link, { headers: { 'User-Agent': UA, 'Accept-Language': 'en-US' }, redirect: 'follow' });
  if (!res.ok) throw new Error(`Google Photos returned ${res.status} for ${link}`);
  const html = await res.text();

  const title = (html.match(/<title>([^<]*?)(?: - Google Photos)?<\/title>/) || [])[1]?.trim();
  if (!title) throw new Error('This does not look like a shared Google Photos album.');
  const cover = (html.match(/<meta property="og:image" content="([^"]+)"/) || [])[1]?.replace(/=[^=/]*$/, '');

  // each photo: ["AF1Qip…", ["https://lh3.googleusercontent.com/pw/…", width, height, …], takenTimestamp, …
  const re = /\["(AF1Qip[\w-]+)",\["(https:\/\/lh3\.googleusercontent\.com\/pw\/[\w-]+)",(\d+),(\d+),[\s\S]*?\]\],(\d{12,14})/g;
  const seen = new Set();
  const photos = [];
  let m, earliest = Infinity;
  while ((m = re.exec(html))) {
    if (seen.has(m[1])) continue;
    seen.add(m[1]);
    photos.push([m[2], +m[3], +m[4]]);
    earliest = Math.min(earliest, +m[5]);
  }
  if (!photos.length) throw new Error('No photos found. Make sure the album is shared with "anyone with the link".');

  const date = Number.isFinite(earliest)
    ? new Date(earliest).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'America/Los_Angeles' })
    : '';
  return { title, cover: cover || photos[0][0], photos, date };
}

async function saveCover(id, coverUrl) {
  await mkdir(COVER_DIR, { recursive: true });
  const res = await fetch(`${coverUrl}=w1200-h900-c`, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error('Could not download the cover photo.');
  await writeFile(path.join(COVER_DIR, `${id}.jpg`), Buffer.from(await res.arrayBuffer()));
  return `assets/images/gallery/${id}.jpg`;
}

const slugify = s => s.toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g, '').trim().replace(/[\s_]+/g, '-').replace(/-+/g, '-');

async function syncAlbum(vault, key, link, overrides = {}) {
  console.log(`Reading ${link} …`);
  const album = await fetchAlbum(link);
  const title = overrides.title || album.title;
  const id = overrides.id || slugify(title);
  const cover = await saveCover(id, album.cover);
  const sealed = await encrypt(key, { link, photos: album.photos });
  const entry = { id, title, date: overrides.date || album.date, count: album.photos.length, cover, ...sealed };

  const i = vault.albums.findIndex(a => a.id === id);
  if (i > -1) vault.albums[i] = entry; else vault.albums.unshift(entry);
  console.log(`  ✓ ${title}: ${album.photos.length} photos`);
}

/* ---------- commands ---------- */
async function main() {
  const vault = await loadVault();

  if (cmd === 'list') {
    if (!vault.albums.length) return console.log('No albums yet.');
    vault.albums.forEach(a => console.log(`${a.id}  ·  ${a.title}  ·  ${a.date}  ·  ${a.count} photos`));
    return;
  }

  if (cmd === 'add') {
    const link = positional[0];
    if (!/^https:\/\/(photos\.app\.goo\.gl|photos\.google\.com)\//.test(link || '')) throw new Error('Give a Google Photos album link, e.g. https://photos.app.goo.gl/…');
    const key = await getKey(vault);
    await syncAlbum(vault, key, link, { title: flag('title'), date: flag('date') });
    await saveVault(vault);
    return console.log('Saved js/gallery-data.js');
  }

  if (cmd === 'refresh') {
    const key = await getKey(vault);
    for (const a of vault.albums) {
      const { link } = await decrypt(key, a);
      await syncAlbum(vault, key, link, { id: a.id, title: a.title, date: a.date });
    }
    await saveVault(vault);
    return console.log('Saved js/gallery-data.js');
  }

  if (cmd === 'remove') {
    const id = positional[0];
    const before = vault.albums.length;
    vault.albums = vault.albums.filter(a => a.id !== id);
    if (vault.albums.length === before) throw new Error(`No album with id "${id}". Run "list" to see ids.`);
    await unlink(path.join(COVER_DIR, `${id}.jpg`)).catch(() => {});
    await saveVault(vault);
    return console.log(`Removed ${id}`);
  }

  console.log('Commands: add <link> [--title "…"] [--date "…"] | refresh | remove <id> | list');
}

main().catch(e => { console.error(`Error: ${e.message}`); process.exit(1); });
